sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
 - docker pull outofcoffee/apiman-wildfly8:1.2.1.Final
script:
 - docker run -d -p 8080:8080 outofcoffee/apiman-wildlfy8:1.2.1.Final
 - ./gradlew test -PintegrationTest --info